ProyectoHotelWebApi/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotelWebApi.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoHotelWebApi/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotelWebApi.Controllers
{
    public class EventoController : Controller
    {
        // GET: Evento
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoHotelWebApi/Controllers/HabitacionController.cs
using System.Web.Mvc;

namespace ProyectoHotelWebApi.Controllers
{
    public class HabitacionController : Controller
    {
        // GET: Habitacion
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoHotelWebApi/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotelWebApi.Controllers
{
    public class HotelController : Controller
    {
        // GET: Hotel
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoHotelWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*    @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })   *@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("INICIO", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Privilegios", "Index", "Privilegios", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Usuarios", "Index", "Usuarios", new { area = "" }, null)</li>
                   
                    <li>@Html.ActionLink("Hoteles", "Index", "Hotel", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Habitaciones", "Index", "Habitacion", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Eventos", "Index", "Evento", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Reservaciones", "Index", "Reservaciones", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Servicios", "Index", "Servicios", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Facturas", "Index", "Facturas", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fernando de León®</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)
</body>
</html>